version: "3.4"

services:
  mssql:
    build: ./db
    container_name: fds-mssql
    environment:
      MSSQL_SA_PASSWORD: "MssqlPass123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: fds-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      "RABBITMQ_DEFAULT_PASS": "rabbitmqpass123"
    ports:
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "25672:25672"

  api:
    container_name: fds-api
    build:
      context: .
      dockerfile: src/FDS.Api/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:6401"
      - "ConnectionStrings__DefaultConnection=user id=sa;password=MssqlPass123;data source=mssql;initial catalog=FDS;Connect Timeout=30;Pooling=true;"
      - "RabbitMQ__Address=rabbitmq"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - 6401:80

  update:
    container_name: fds-update
    build:
      context: .
      dockerfile: ./src/Services/FDS.Version.Service/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:6501"
      - "ConnectionStrings__DefaultConnection=user id=sa;password=MssqlPass123;data source=mssql;initial catalog=FDS;Connect Timeout=30;Pooling=true;"
      - "RabbitMQ__Address=rabbitmq"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - 6501:80
